### ISSUE TITLE
Why does PCQueue have an endless loop in Read and Write functions?

### ISSUE THREAD

**Issue by ralemy** [freezer333/nodecpp-demo#10]
In the declaration of PCQueue, both read and write data functions have a [while(true)](https://github.com/freezer333/nodecpp-demo/blob/3878593c28c91de9a9d5d613a310cd06eb4fd1f1/streaming/dist/streaming-worker.h#L20) in them. both also return from within the body of those while loops. 

would you mind telling me why these while loops were added please?

**Comment by freezer333** [comment]
Just a mistake... I think that loop structure was left over from a previous version and since it had no effect, never showed up on any testing....  Thanks!
