### ISSUE TITLE
ObjectWrap

### ISSUE THREAD

**Issue by BiancoA** [freezer333/nodecpp-demo#13]
I was comparing the object wrap that you proposed in 
https://github.com/freezer333/nodecpp-demo/blob/master/objectwrap/polynomial.cpp

with the proposed version in node.js docs: https://nodejs.org/api/addons.html

and I see that there is quite a difference in the `Init(v8::Local<v8::Object> exports)` function: while you get the `v8::FunctionTemplate` from the as

```
        Local<FunctionTemplate> tpl = FunctionTemplate::New(isolate, New);
```
where `isolate` is isolated (sorry) from `exports`, they:

```
  v8::Local<v8::FunctionTemplate> tpl = Nan::New<v8::FunctionTemplate>(New);
```

create a brand new one.

It is not clear what version should be preferred. Is it explained in some part of your book? could you reference it?

Thanks!

**Comment by freezer333** [comment]
Not sure exactly where you are getting the `Nan::New<v8::FunctionTemplate>(New)` example from - but in that line of code Nan is being used, and its actually still using the isolate behind the scenes - its a macro function I believe...  They should be equivalent, its just that one is explicitly using Nan.

**Comment by BiancoA** [comment]
sorry, I copy-pasted the wrong example, the one from the docs is as you suggest: 

```
void MyObject::Init(Local<Object> exports) {
  Isolate* isolate = exports->GetIsolate();

  // Prepare constructor template
  Local<FunctionTemplate> tpl = FunctionTemplate::New(isolate, New);
...
}
```
