### ISSUE TITLE
Calling c library function in addon

### ISSUE THREAD

**Issue by navaneetharaopy** [freezer333/nodecpp-demo#2]
Hi, 
    Is it possible to call c/c++ library function from addon. If yes , please provide a code snippet. 

Thanks

**Comment by freezer333** [comment]
Yes, it is - it really doesn't require any special V8 code, but your c library needs to be setup so C++ can call it.  Checkout [https://github.com/freezer333/cppwebify-tutorial](https://github.com/freezer333/cppwebify-tutorial) - the addon segment of the tutorial demonstrates calling a C function.
