### ISSUE TITLE
Node.js standard callback signature

### ISSUE THREAD

**Issue by sulliwane** [freezer333/nodecpp-demo#3]
Hi,

If the addon respects the [standard callback signature](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/), it can then easily be promisified (using [bluebird](http://bluebirdjs.com/docs/getting-started.html) **promisify** for example). But I noticed on this example that there is no error parameter: https://github.com/freezer333/nodecpp-demo/blob/master/buffers/index.js

``` javascript
function(bmp_buffer) {
```

maybe you could consider adding the error parameter? (especially if this make it into the ebook :)

**Comment by freezer333** [comment]
Makes perfect sense, I've modified the callback in the top level async example and in the buffers example.  Thanks for the tip!
